# .github/workflows/deploy.yml
name: Deploy Tempero

on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  migrate-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: tempero/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./tempero

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Supabase PROD project
        working-directory: ./tempero
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROD_REF: ${{ secrets.SUPABASE_PROD_REF }}
        run: |
          supabase link --project-ref $SUPABASE_PROD_REF

      - name: Apply Supabase migrations to PROD
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        working-directory: ./tempero
        run: |
          supabase db push


      - name: Set PROD env vars for build
        run: |
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL_PROD }}" >> $GITHUB_ENV
          echo "VITE_SUPABASE_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY_PROD }}" >> $GITHUB_ENV

      - name: Build app
        run: npm run build
        working-directory: ./tempero

<<<<<<< HEAD
      - name: Set up git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
=======
      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"


>>>>>>> 5062adc3810254306ba26aec13855c3deff81937
      -  name: Deploy to GitHub Pages
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           REPO: ${{ github.repository }}  # e.g. MESW-LES-2025/Tempero
         run: |
           npx gh-pages -d dist -r https://x-access-token:${GITHUB_TOKEN}@github.com/$REPO.git
         working-directory: ./tempero
